### Option:Plugins.EmberPlus.System.Path
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:

### Option:Plugins.EmberPlus.Timeout
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:
