### Option:Plugins.EmberPlus.System.Path
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:
# Plugins.EmberPlus.System.Path=

### Option: Plugins.EmberPlus.Timeout
#   Legacy fallback timeout value. The maximum time (in seconds) for an item
#	check to be performed, or connection to be made.
#   This value is only used for item checks coming from Zabbix server
#   versions older than 7.0. For newer versions, item check timeout can be
#   configured in the frontend.
#   
#   For connection timeout use ConnectionTimeout found below.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.EmberPlus.Timeout=<Global timeout>

### Option: Plugins.EmberPlus.KeepAlive
#	Time in seconds for waiting before unused connections will be closed.
#
# Mandatory: no
# Range: 60-900
# Default:
# Plugins.EmberPlus.KeepAlive=300

### Option: Plugins.EmberPlus.Sessions.*.Uri
#	Uri to connect.
#   Connection is done over tcp no need to specify scheme.
#	Replace "*" with a session name.
#
# Mandatory: no
# Range:
#   Must matches the URI format.
#   Embedded credentials will be ignored.
# Default: localhost:9998
# Plugins.EmberPlus.Sessions.*.Uri=

### Option: Plugins.EmberPlus.Sessions.*.ConnectionTimeout
#	Amount of time to wait for a server to respond when first connecting.
#   Replace "*" with a session name.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.EmberPlus.Sessions.*.ConnectionTimeout=<Global timeout from Zabbix agent 2 configuration file>

### Option: Plugins.EmberPlus.Default.Uri
#	Uri to connect.
#   Default value used if no other is specified.
#
# Mandatory: no
# Range:
#   Must matches the URI format.
#   Connection is done over tcp no need to specify scheme.
#   Embedded credentials will be ignored.
# Default: localhost:9998
# Plugins.EmberPlus.Default.Uri=

### Option: Plugins.EmberPlus.Default.ConnectionTimeout
#	Amount of time to wait for a server to respond when first connecting.
#   Default value used if no other is specified.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.EmberPlus.Default.ConnectionTimeout=<Global timeout>
