### Option:Plugins.EmberPlus.System.Path
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:

### Option:Plugins.EmberPlus.Timeout
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:
Plugins.EmberPlus.Timeout=3
Plugins.EmberPlus.KeepAlive=60
Plugins.EmberPlus.System.Path=C:\Users\EriksSneiders\work\ember-plus\ember-plus.exe
